Report actual error when import fails in mplotqueries.
Before:

% ~/.local/bin/mplotqueries ./mongod.log
Traceback (most recent call last):
  File "/home/w/.local/bin/mplotqueries", line 7, in <module>
    from mtools.mplotqueries.mplotqueries import main
  File "/home/w/.local/lib/python2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 22, in <module>
    raise ImportError("Can't import matplotlib. See "
ImportError: Can't import matplotlib. See github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.

OK, let's see what the deal is with matplotlib:

averagest% python
Python 2.7.15 (default, May  1 2018, 05:55:50)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib
<module 'matplotlib' from '/home/w/.local/lib/python2.7/site-packages/matplotlib/__init__.pyc'>
>>>

Hmm, it seems fine. What needs to be done?

After:

% ~/.local/bin/mplotqueries ./mongod.log
Traceback (most recent call last):
  File "/home/w/.local/bin/mplotqueries", line 7, in <module>
    from mtools.mplotqueries.mplotqueries import main
  File "/home/w/.local/lib/python2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 27, in <module>
    "web browser. Error: " + str(e))
ImportError: Can't import matplotlib. See github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser. Error: No module named _tkinter, please install the python-tk package

Thanks, helpful error message!

Fixes #620